"""initial migration

Revision ID: 784b9d52385e
Revises: ad042b068179
Create Date: 2016-11-30 21:14:17.274029

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '784b9d52385e'
down_revision = 'ad042b068179'
branch_labels = None
depends_on = None


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('body_html', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'body_html')
    ### end Alembic commands ###
